# Комментарии
## Создать комментарий
POST http://localhost:4000/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4nxE
Content-Type: application/json

{
  "text": "You can gaze at the stars and listen to the sounds of nature from your cozy warm bed",
  "rating": 5,
  "offerId": "64998ca950ea85de6e1fa9e5"
}

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/64998ca950ea85de6e1fa9e5/comments HTTP/1.1

###
