# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@overlook.net",
  "avatarPath": "torrance.png",
  "name": "Keks",
  "isPro": false,
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/649066da856f0181cf2b7dde/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4nxE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="image.png"
Content-Type: image/png

< ./static/default-avatar2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Проверить токен пользователя## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAb3Zlcmxvb2submV0IiwiaWQiOiI2NDkxODdmYjZlYTE1ZmIwNmEzYjdiODEiLCJpYXQiOjE2ODcyNTkzNDcsImV4cCI6MTY4NzQzMjE0N30.FxnDOmbkjKSz9Qn-MoTx6ZTkNWvvJzV-Pg6l1t7_fHc

###

## Выход из закрытой части приложения (5.10)
DELETE http://localhost:4000/users/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzQxNDMxNiwiZXhwIjoxNjg3NTg3MTE2fQ.EzoLxnS7qtvwcGrvLlgK-r8BgDTvSBoCXcTBmUWL4vw
###
